### ISSUE TITLE
v1.5.0 not in __init__.py 

### ISSUE THREAD

**Issue by FitzgeraldKrudde** [ing-bank/doing-cli#113]
The __init__.py  does not contain 1.5.0 but still 1.4.0 though version 1.5.0 has been released.

See: https://github.com/ing-bank/doing-cli/blob/main/src/doing/__init__.py

Interestingly the release 1.5.0 contains this commit which updates the version to 1.5.0 but this commit has this message in Github:
`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

See: https://github.com/ing-bank/doing-cli/commit/12132a6c0503a565f61dae5787ff157c013b1a67

**Comment by operte** [comment]
I might have messed up something, thanks for noticing. 
I don't think this is something I can fix, though, because the release has been made. I'll make sure that the next release goes back to correct version numbers on this file.

I am not sure that the version number in `__init__.py` matters for anything, btw. Do you know if it does?

**Comment by FitzgeraldKrudde** [comment]
I don't know but doing-cli works fine :-)
Fixing is in next release sounds good.
I just created this issue to notify.

**Comment by operte** [comment]
Fixed!
