### ISSUE TITLE
Add a parameter to `workon` for setting a different source branch to create the new branch from

### ISSUE THREAD

**Issue by tijlk** [ing-bank/doing-cli#49]
I have a couple of migrations going right now, that are forcing us to (temporarily) work from a different branch than the master branch. This means that we're creating feature branches from another branch (let's call it `develop`) and are creating pull requests to that `develop` branch as well, instead of to the default branch (`master`).

It would be helpful if you could:

* set a source branch in the call to workon, e.g. `doing workon "adding feature X" -b develop`
* set a specific branch to always use in `.doing-cli-config.yml`, e.g.: `default_branch: develop`

**Comment by timvink** [comment]
Some technical notes on the implementation of this issue:

github cli has [`gh pr create`](https://cli.github.com/manual/gh_pr_create), that has the options:

```
-B, --base branch          The branch into which you want your code merged
-H, --head branch          The branch that contains commits for your pull request (default: current branch)
```

`doing create pr` has a slightly different flow, because it takes a `workitem_id` as an input to create a local branch, a remote branch and PR.  Source and target branches are not sufficiently clear yet.

For creating branches, azure devops has [`az repos ref create`](https://docs.microsoft.com/en-us/cli/azure/repos/ref?view=azure-cli-latest) with the option

```
--object-id
Id of the object to create the reference from.
```

On `doing pr create`, I create a new remote branch if it doesn't exist.  Currently, I don't specify `--object-id`  and I am actually not sure if it's using the default branch (`master`?) or the current local branch.

Because `doing pr create` works differently than `gh pr create`, using the parameters `source_branch` (defaults to current branch) and `target_branch` (defaults to [default branch](https://docs.microsoft.com/en-us/azure/devops/repos/git/change-default-branch?view=azure-devops)) seems to make more sense.

I should also check to make sure commits on local `source_branch` are already pushed to `origin/source_branch` before creating a remote branch.

Devops allows you to [set a default branch](https://dev.azure.com/IngEurCDaaS01/IngOne/_git/P01908-taco/branches) per repository. You can also do this programmatically via [`az repos update`](https://docs.microsoft.com/en-us/cli/azure/repos?view=azure-cli-latest#az_repos_update), which means we can take the same approach as #53 and on every command that uses the default branch (probably best to write a separate function for that), if `default_branch` is specified in the `.doing-cli-config.yml`, we set that just in case. 

So, the approach would be to:

- Add option to set a `default_branch`
- Add `source_branch` and `target_branch` to `doing pr create` and `doing workon`
- Update docs with examples

**Comment by timvink** [comment]
I don't currently use DevOps for my work, so not interesting for me to develop this (nor could I test it). 

@operte this one would be a nice improvement to doing-cli

**Comment by operte** [comment]
@FitzgeraldKrudde proposed a simple solution for this #107 
This adds the option of choosing a different `default_branch` when using `doing pr create` and `doing workon`. The branch is branched from that `default_branch` and it is also merged to it.

We thought that in the majority of situations one wishes to branch from and merge to the same branch. Other situations can still be manually tuned by the user. 
This was a good compromise, instead of adding too many options to the commands.
